### ISSUE TITLE
Using a mqtt hostname with an underscore causes exception error.

### ISSUE THREAD

**Issue by nmarus** [sitewhere/sitewhere#539]
Tested on 1.11 and 1.12

When setting the mqtt host name in SiteWhere to use a name with underscores, for example "mqtt_cluster_lb", I get the error:

```
Exception in thread "MQTT Task" java.lang.IllegalArgumentException: hostname can't be null
at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
at org.fusesource.hawtdispatch.transport.TcpTransport$2.run(TcpTransport.java:458)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```
This same error repeats for the 3 inbound event processors and 3 outbound command processors when SiteWhere tries initiate them. After each, something like the following is logged:

```
2017-09-10T05:38:42,072 [Tenant Lifecycle 1] ERROR [MqttInboundEventReceiver] MqttInboundEventReceiver state transitioned to ERROR.
com.sitewhere.spi.SiteWhereException: Unable to connect to MQTT broker.
```

To verify it is not a DNS, network, or firewall issue, from bash shell of SiteWhere host, I can ping/mqtt-subscribe/mqtt-publish to the underscore'd hostname and it works correctly.

I can also change the sitewhere mqtt tenant config to something like "mqttclusterlb" and do a temporary workaround so that this name resolves from the sitewhere host, and everything works properly.  

For context, the underscores are part of a how a docker stack environment does service discovery to the mqtt cluster stack i.e `<stack name>_<stack service>`. Otherwise, I'd just simply change hostnames. :)

If you need any other details, let me know.

**Comment by derekadams** [comment]
I think the bug is related to this:

https://stackoverflow.com/questions/28568188/java-net-uri-get-host-with-underscores

I'm surprised we have not run into this one before now, but I'm sure there is a workaround. Will take a look and try to get a patch out ASAP.

**Comment by derekadams** [comment]
FYI, the Docker guys are trying to figure out the right approach since underscores are technically not allowed in host names:

https://github.com/docker/distribution/issues/2160
https://github.com/docker/compose/issues/229

Since SiteWhere 2.0 is going to be using Docker Compose and/or stack as its default deployment mechanism, we will need to figure out a workaround across the board for this one. The root of the problem is that a java.net.URI returns null for host name if you feed it a full URL with an underscore in the host section.

**Comment by nmarus** [comment]
Quick update, I got around this in a docker-compose file for a swarm stack by using aliases for the service. Docker docs here: https://docs.docker.com/compose/compose-file/#aliases

Simple docker-compose.yml example of workaround below. This is where if I created this as a stack called `mqtt-cluster`, I was previously trying to access it from a separate SiteWhere stack using the dynamic generated dns name of `mqtt-cluster_loadbalancer` (which triggered the above error). With the use of aliases from the link above, I can now access as `mqtt-cluster-loadbalancer` using the alias on the network shared between stacks. 

```yaml
version: '3.2'
services:
  loadbalancer:
    [...]
    networks:
      internal:
      tenant-net:
        aliases:
          - mqtt-cluster-loadbalancer
    ports:
      - "8883:8883"
  node01:
    [...]
    networks:
      - internal
  node02:
    [...]
    networks:
      - internal
  node03:
    [...]
    networks:
      - internal
networks:
  internal:
  tenant-net:
    external:
      name: tenant-net
```
